### ISSUE TITLE
Update Travis configuration so that it does not compile Rakudo every single time.

### ISSUE THREAD

**Issue by JJ** [Raku/problem-solving#85]
The [official Travis configuration for Perl 6](https://docs.travis-ci.com/user/languages/perl6/) uses Rakudobrew to download from source and then compiles. Every single time.

We would need either
* Precompiled binaries we can download directly, with an URL that can be generated automatically from version.
* Docker containers. That might be tricky to install dependencies.

If there's any other option, or you prefer any of those above, please let us know.

**Comment by AlexDaniel** [comment]
Just for the record, whateverable builds are available publicly. For example: https://whateverable.6lang.org/HEAD. However, they're built with a very recent version of glibc so they don't work on Travis. Somebody has to do it properly, and I'm even ready to store them, but it'll take a few weeks to get the amount of builds I currently have for whateverable. Though maybe for Travis it doesn't matter.

**Comment by patzim** [comment]
In most cases it makes sense to use a Rakudo release (in contrast to latest master) when testing a module. So given we actually start providing official binary builds of releases (I hope we do!), we could just use those in the Travis config.

**Comment by nxadm** [comment]
Here are instructions to use packages:
https://github.com/nxadm/rakudo-pkg#using-rakudo-pkg-on-travis

**Comment by patzim** [comment]
Who has privileges to change the 'perl6' configuration?

We have two working solutions (docker containers that @JJ provides, and rakudo-pkg that @nxadm provides), so all that's needed is for someone to update the Travis configuration to use one of the two. Personally I'd go with rakudo-pkg, as it's the more conventional solution.

**Comment by nxadm** [comment]
Traditionally, a regular travis setup looks like this:
```yaml
language: raku
raku:
- latest
# - 2019.x
- "2019.07.1"
- "2019.07"
- "2019.3"
...
```

However, if there one could also play with the prefix:
```yaml
language: raku
raku:
# What regular users would probably use
- latest
- 2019.07.1
- 2018.03
# Advanced cases:
# from git
- branch-master
- branch-6f
# from docker
- docker-star:tag 
```
For my use case packages that include zef are enough, but maybe a more flexible system can be useful for some people.
